{
 "title": "Neptune Apex",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_current_probe_value{probe=\"Tmp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tank Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "apex_current_probe_value{probe=\"Tmp\"}",
     "legendFormat": "Tank Temperature"
    }
   ]
  },
  {
   "title": "Current Tank pH",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_current_probe_value{probe=\"pH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tank pH",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "expr": "apex_current_probe_value{probe=\"pH\"}",
     "legendFormat": "Tank pH"
    }
   ]
  },
  {
   "title": "Current Calcium Reactor pH",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apex_current_probe_value{probe=\"CRPh\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calcium Reactor pH",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "expr": "apex_current_probe_value{probe=\"CRPh\"}",
     "legendFormat": "Calcium Reactor pH"
    }
   ]
  },
  { "title": "Outlets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Outlet State",
   "type": "bargauge",
   "description": "Off, On, Auto Off, Auto On",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apex_current_outlet_state", "legendFormat": "{{outlet}}" }
   ]
  }
 ]
}