services:
  apex-collector:
    container_name: apex-collector
    image: dockerhost.briangautreau.com:5000/apex_collector:latest
    ports:
      - "9141:9141"
    volumes:
      - "/root/apex_collector/.env:/go/.env"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:9141/metrics"]
      interval: 300s
      retries: 5
      timeout: 10s
    restart: always
